const ResponseFields = {
    data: "data",
    messege: "messege",
    catch: "catch",
    error: "error",
    cussor: "cussor",
    did: "Did",
    userInfo: "userInfo",
    customerInfo: "customerInfo",
    kiotInfo: "kiotInfo",
    productInfo: "productInfo",
    imageInfo: "imageInfo",
    transactiontInfo: "transactiontInfo",
    saleOffInfo: "saleOffInfo",
    productList: "productList",
    acceptToken: "acceptToken",
    customerList: "customerList",
    accountList: "accountList",
    transactionList: "transactionList",
    saleOffProductList: "saleOffProductList",
    saleOffTransactionList: "saleOffTransactionList",
    kiotList: "kiotList",
    imageList:"imageList",
    CodeMessage: "CodeMessage",
}

export { ResponseFields };